# Generated by rzig::document(). Do not edit.

#' Compute a Pearson correlation matrix using pure Zig worker threads.
#' @param data A double matrix with observations in rows and variables in columns.
#' @return A symmetric variable-by-variable correlation matrix.
#'
#' @export
correlation_matrix <- function(data) {
  .Call(correlation_matrix_, data)
}

#' Estimate an undirected Gaussian PC-stable skeleton.
#' @param data A double matrix with observations in rows and variables in columns.
#' @param alpha The two-sided Gaussian conditional-independence level.
#' @param max_depth The maximum conditioning-set size, from zero through five.
#' @return A symmetric logical adjacency matrix with a false diagonal.
#'
#' @export
pc_skeleton <- function(data, alpha, max_depth) {
  .Call(pc_skeleton_, data, alpha, max_depth)
}
