edge_bindings <- function() {
  text <- read_bytes(fixture_path("edge.zig"))
  exports <- structure(rzig:::.rzig_scan_text(text, "edge.zig"), class = "rzig_exports", package = "edgepkg")
  render_bindings(exports)
}

test_that("rendered bindings match the files generated by the Zig scanner", {
  bindings <- edge_bindings()
  expect_identical(charToRaw(bindings$manifest), charToRaw(read_bytes(fixture_path("edge", "manifest.zig"))))
  expect_identical(charToRaw(bindings$wrappers), charToRaw(read_bytes(fixture_path("edge", "rzig-wrappers.R"))))
  expect_identical(charToRaw(bindings$namespace), charToRaw(read_bytes(fixture_path("edge", "NAMESPACE"))))
})

test_that("the rendered wrappers and NAMESPACE block parse", {
  bindings <- edge_bindings()
  expect_silent(parse(text = bindings$wrappers, keep.source = FALSE))
  expect_silent(parse(text = bindings$namespace, keep.source = FALSE))
})

test_that("an empty export list renders an empty manifest", {
  exports <- structure(list(), class = "rzig_exports", package = "emptypkg")
  bindings <- render_bindings(exports)
  expect_true(grepl("pub const exports = .{};", bindings$manifest, fixed = TRUE))
  expect_identical(bindings$wrappers, "# Generated by rzig::document(). Do not edit.\n")
  expect_identical(
    bindings$namespace,
    "# Generated by rzig::document(): begin\nuseDynLib(\"emptypkg\"\n)\n# Generated by rzig::document(): end\n"
  )
})

test_that("Zig string escaping matches the Zig formatter", {
  value <- paste0("a\"b\\c\nd\te\rf\x01g", "\u0142", "h'i")
  expect_identical(
    rzig:::.rzig_zig_string(value),
    "\"a\\\"b\\\\c\\nd\\te\\rf\\x01g\\xc5\\x82h'i\""
  )
})

test_that("R identifiers are quoted when needed", {
  expect_identical(rzig:::.rzig_r_identifier("add_values"), "add_values")
  expect_identical(rzig:::.rzig_r_identifier(".hidden"), ".hidden")
  expect_identical(rzig:::.rzig_r_identifier("if"), "`if`")
  expect_identical(rzig:::.rzig_r_identifier("x-value"), "`x-value`")
  expect_identical(rzig:::.rzig_r_identifier("a`b\\c"), "`a\\`b\\\\c`")
  expect_identical(rzig:::.rzig_r_identifier(".1x"), "`.1x`")
})

test_that("native aliases avoid export names", {
  exports <- lapply(c("foo", "foo_", "r-name"), function(name) list(name = name))
  expect_identical(rzig:::.rzig_native_aliases(exports), c(".rzig_symbol_1", "foo__", ".rzig_symbol_3"))
})

test_that("render_bindings rejects other inputs", {
  expect_error(render_bindings(list()), "scan_exports")
  exports <- structure(list(), class = "rzig_exports", package = "ok")
  expect_error(render_bindings(exports, package = "1bad"), "package name")
})
