test_that("use_rzig scaffolds a package and generates bindings without Zig", {
  path <- local_package("scaffoldpkg")
  scaffold <- use_rzig(path)
  expect_s3_class(scaffold, "rzig_scaffold")
  expect_identical(scaffold$package, "scaffoldpkg")
  expect_true(all(file.exists(file.path(path, c(
    "configure", "configure.win", "cleanup", "cleanup.win",
    file.path("src", "entry.c"), file.path("src", "Makevars.in"),
    file.path("src", "Makevars.win.in"),
    file.path("src", "rzig", "framework", "rzig.zig"),
    file.path("src", "rzig", "src", "main.zig"),
    file.path("R", "rzig-wrappers.R"), "NAMESPACE"
  )))))
  expect_identical(vapply(scaffold$exports, function(item) item$name, character(1L)), "hello_zig")
  expect_true(any(grepl("R_init_scaffoldpkg", readLines(file.path(path, "src", "entry.c")))))
  expect_output(print(scaffold), "hello_zig")
  expect_error(use_rzig(path), "overwrite = TRUE")
  expect_s3_class(use_rzig(path, overwrite = TRUE), "rzig_scaffold")
})

test_that("document writes the three generated files and keeps foreign NAMESPACE lines", {
  path <- local_package("docpkg")
  use_rzig(path)
  writeLines(
    c("importFrom(stats, median)", readLines(file.path(path, "NAMESPACE"))),
    file.path(path, "NAMESPACE")
  )
  bindings <- document(path)
  expect_s3_class(bindings, "rzig_bindings")
  expect_identical(bindings$files, c(
    file.path("src", "rzig", "framework", "generated", "manifest.zig"),
    file.path("R", "rzig-wrappers.R"),
    "NAMESPACE"
  ))
  namespace <- readLines(file.path(path, "NAMESPACE"))
  expect_identical(namespace[[1L]], "importFrom(stats, median)")
  expect_identical(sum(namespace == "# Generated by rzig::document(): begin"), 1L)
  expect_true("export(\"hello_zig\")" %in% namespace)
  expect_identical(charToRaw(read_bytes(file.path(path, "R", "rzig-wrappers.R"))), charToRaw(bindings$wrappers))
  expect_identical(
    charToRaw(read_bytes(file.path(path, "src", "rzig", "framework", "generated", "manifest.zig"))),
    charToRaw(bindings$manifest)
  )
  expect_output(print(bindings), "hello_zig <- function(name)", fixed = TRUE)
})

test_that("document picks up edited Zig exports", {
  path <- local_package("editpkg")
  use_rzig(path)
  main <- file.path(path, "src", "rzig", "src", "main.zig")
  writeLines(c(
    "const std = @import(\"std\");",
    "const builtin = @import(\"builtin\");",
    "const rzig = @import(\"rzig\");",
    "",
    "pub const panic = if (builtin.is_test)",
    "    std.debug.FullPanic(std.debug.defaultPanic)",
    "else",
    "    rzig.Panic;",
    "",
    "/// Add two numeric vectors elementwise.",
    "/// @param a The first numeric vector.",
    "/// @param b The second numeric vector.",
    "/// @return The elementwise sums.",
    "/// @export",
    "pub fn add_vectors(",
    "    ctx: *rzig.Ctx,",
    "    a: []const f64,",
    "    b: []const f64,",
    ") rzig.Error![]f64 {",
    "    if (a.len != b.len) {",
    "        return rzig.raise(\"lengths differ: {d} vs {d}\", .{ a.len, b.len });",
    "    }",
    "    const result = try ctx.alloc(f64, a.len);",
    "    for (a, b, result) |left, right, *value| value.* = left + right;",
    "    return result;",
    "}",
    "",
    "comptime {",
    "    rzig.registerModule(@This());",
    "}"
  ), main)
  exports <- scan_exports(path)
  expect_identical(exports[[1L]]$name, "add_vectors")
  expect_identical(exports[[1L]]$parameters, c("a", "b"))
  document(path)
  wrappers <- readLines(file.path(path, "R", "rzig-wrappers.R"))
  expect_true("add_vectors <- function(a, b) {" %in% wrappers)
  expect_true("#' @param a The first numeric vector." %in% wrappers)
  expect_false(any(grepl("hello_zig", wrappers, fixed = TRUE)))
  namespace <- readLines(file.path(path, "NAMESPACE"))
  expect_true("export(\"add_vectors\")" %in% namespace)
  expect_false(any(grepl("hello_zig", namespace, fixed = TRUE)))
})

test_that("rzig_status reports each step and detects stale bindings", {
  path <- local_package("statuspkg")
  use_rzig(path)
  status <- rzig_status(path)
  expect_s3_class(status, "rzig_status")
  expect_identical(status$step, c("DESCRIPTION", "Scaffold", "Zig source", "Exports", "Bindings", "Zig compiler"))
  expect_true(all(status$ok[1:5]))
  main <- file.path(path, "src", "rzig", "src", "main.zig")
  text <- readLines(main)
  text <- sub("pub fn hello_zig(", "pub fn renamed(", text, fixed = TRUE)
  writeLines(text, main)
  stale <- rzig_status(path)
  expect_false(stale$ok[stale$step == "Bindings"])
  expect_match(stale$detail[stale$step == "Bindings"], "out of date")
  document(path)
  expect_true(rzig_status(path)$ok[5L])
  expect_output(print(status), "Exports")
})

test_that("rzig_status describes a directory without a scaffold", {
  path <- local_package("barepkg")
  status <- rzig_status(path)
  expect_false(status$ok[status$step == "Scaffold"])
  expect_false(status$ok[status$step == "Zig source"])
})

test_that("scan_exports and document need the scaffold", {
  path <- local_package("noscaffold")
  expect_error(scan_exports(path), "use_rzig")
  expect_error(document(path), "use_rzig")
})

test_that("generated files use LF and CRLF sources are scanned", {
  path <- local_package("crlfpkg")
  use_rzig(path)
  main <- file.path(path, "src", "rzig", "src", "main.zig")
  text <- gsub("\n", "\r\n", read_bytes(main), fixed = TRUE, useBytes = TRUE)
  connection <- file(main, open = "wb")
  writeBin(charToRaw(text), connection)
  close(connection)
  namespace_path <- file.path(path, "NAMESPACE")
  namespace <- gsub("\n", "\r\n", read_bytes(namespace_path), fixed = TRUE, useBytes = TRUE)
  connection <- file(namespace_path, open = "wb")
  writeBin(charToRaw(namespace), connection)
  close(connection)
  expect_true(rzig_status(path)$ok[5L])
  exports <- scan_exports(path)
  expect_identical(exports[[1L]]$name, "hello_zig")
  expect_false(grepl("\r", exports[[1L]]$doc, fixed = TRUE))
  document(path)
  for (file in c(file.path("R", "rzig-wrappers.R"), "NAMESPACE",
                 file.path("src", "rzig", "framework", "generated", "manifest.zig"))) {
    expect_false(grepl("\r", read_bytes(file.path(path, file)), fixed = TRUE), info = file)
  }
})
