//! GENERATED by tools/scan.zig - do not edit.
//! Regenerate with `zig build gen` or `rzig::document()`.

/// Bind exported function names to the package's root Zig module.
pub fn Bind(comptime root: type) type {
    return struct {
        const bound_root = root;

        /// Metadata for public functions exposed through RZig.
        pub const exports = .{
            .{
                .name = "add_values",
                .func = bound_root.add_values,
                .doc = "Add \"values\".\nPreserves \\ paths and \"quotes\".\n@param left The left-hand value.\n@param `right` The right-hand value, documented with backticks.\n@return The sum.",
                .parameters = .{ "left", "right" },
            },
            .{
                .name = "r-name",
                .func = bound_root.@"r-name",
                .doc = "",
                .parameters = .{ "x-value", "if" },
            },
            .{
                .name = "tag_first",
                .func = bound_root.tag_first,
                .doc = "Tag-first documentation after a blank doc line.\n",
                .parameters = .{"value"},
            },
            .{
                .name = "only_tags",
                .func = bound_root.only_tags,
                .doc = "@param values Documented without a description sentence.",
                .parameters = .{"values"},
            },
            .{
                .name = "spaced",
                .func = bound_root.spaced,
                .doc = "Documented across a plain comment and a blank line.",
                .parameters = .{"n"},
            },
            .{
                .name = "multi",
                .func = bound_root.multi,
                .doc = "Multi-line parameters with comments inside the list.\n@param data Observations in rows.",
                .parameters = .{ "data", "labels", "flag" },
            },
            .{
                .name = "nothing",
                .func = bound_root.nothing,
                .doc = "Zero parameters and unicode: \xc5\x81ojasiewicz \xc5\xbc \xe2\x88\x91.",
                .parameters = .{},
            },
            .{
                .name = "foo",
                .func = bound_root.foo,
                .doc = "Name whose preferred alias collides with another export.",
                .parameters = .{ "values", "factor" },
            },
            .{
                .name = "foo_",
                .func = bound_root.foo_,
                .doc = "Export named like the alias of `foo`.",
                .parameters = .{"x"},
            },
            .{
                .name = "twice",
                .func = bound_root.twice,
                .doc = "Inline declaration.",
                .parameters = .{"value"},
            },
            .{
                .name = "summarize",
                .func = bound_root.summarize,
                .doc = "Returns a list.\n@return A named list.",
                .parameters = .{"values"},
            },
        };
    };
}
