# Generated by rzig::document(). Do not edit.

#' Add "values".
#' Preserves \ paths and "quotes".
#' @param left The left-hand value.
#' @param `right` The right-hand value, documented with backticks.
#' @return The sum.
#'
#' @export
add_values <- function(left, right) {
  .Call(add_values_, left, right)
}

#' Call `r-name` in Zig.
#'
#' @param `x-value` A value passed to the Zig implementation.
#' @param `if` A value passed to the Zig implementation.
#' @return The value returned by the Zig implementation.
#' @export
`r-name` <- function(`x-value`, `if`) {
  .Call(.rzig_symbol_2, `x-value`, `if`)
}

#' Tag-first documentation after a blank doc line.
#'
#'
#' @param value A value passed to the Zig implementation.
#' @return The value returned by the Zig implementation.
#' @export
tag_first <- function(value) {
  .Call(tag_first_, value)
}

#' Call only_tags in Zig.
#' @param values Documented without a description sentence.
#'
#' @return The value returned by the Zig implementation.
#' @export
only_tags <- function(values) {
  .Call(only_tags_, values)
}

#' Documented across a plain comment and a blank line.
#'
#' @param n A value passed to the Zig implementation.
#' @return The value returned by the Zig implementation.
#' @export
spaced <- function(n) {
  .Call(spaced_, n)
}

#' Multi-line parameters with comments inside the list.
#' @param data Observations in rows.
#'
#' @param labels A value passed to the Zig implementation.
#' @param flag A value passed to the Zig implementation.
#' @return The value returned by the Zig implementation.
#' @export
multi <- function(data, labels, flag) {
  .Call(multi_, data, labels, flag)
}

#' Zero parameters and unicode: Łojasiewicz ż ∑.
#'
#' @return The value returned by the Zig implementation.
#' @export
nothing <- function() {
  .Call(nothing_)
}

#' Name whose preferred alias collides with another export.
#'
#' @param values A value passed to the Zig implementation.
#' @param factor A value passed to the Zig implementation.
#' @return The value returned by the Zig implementation.
#' @export
foo <- function(values, factor) {
  .Call(.rzig_symbol_8, values, factor)
}

#' Export named like the alias of `foo`.
#'
#' @param x A value passed to the Zig implementation.
#' @return The value returned by the Zig implementation.
#' @export
foo_ <- function(x) {
  .Call(foo__, x)
}

#' Inline declaration.
#'
#' @param value A value passed to the Zig implementation.
#' @return The value returned by the Zig implementation.
#' @export
twice <- function(value) {
  .Call(twice_, value)
}

#' Returns a list.
#' @return A named list.
#'
#' @param values A value passed to the Zig implementation.
#' @export
summarize <- function(values) {
  .Call(summarize_, values)
}
