//! Generates the C translation unit that verifies RZig's hard-coded R ABI
//! constants against the headers used to build an R package.

const std = @import("std");
const abi = @import("abi.zig");

const Constant = struct {
    name: []const u8,
    expression: []const u8,
    value: i64,
};

const constants = [_]Constant{
    .{ .name = "NILSXP", .expression = "NILSXP", .value = abi.NILSXP },
    .{ .name = "SYMSXP", .expression = "SYMSXP", .value = abi.SYMSXP },
    .{ .name = "LISTSXP", .expression = "LISTSXP", .value = abi.LISTSXP },
    .{ .name = "CLOSXP", .expression = "CLOSXP", .value = abi.CLOSXP },
    .{ .name = "ENVSXP", .expression = "ENVSXP", .value = abi.ENVSXP },
    .{ .name = "PROMSXP", .expression = "PROMSXP", .value = abi.PROMSXP },
    .{ .name = "LANGSXP", .expression = "LANGSXP", .value = abi.LANGSXP },
    .{ .name = "SPECIALSXP", .expression = "SPECIALSXP", .value = abi.SPECIALSXP },
    .{ .name = "BUILTINSXP", .expression = "BUILTINSXP", .value = abi.BUILTINSXP },
    .{ .name = "CHARSXP", .expression = "CHARSXP", .value = abi.CHARSXP },
    .{ .name = "LGLSXP", .expression = "LGLSXP", .value = abi.LGLSXP },
    .{ .name = "INTSXP", .expression = "INTSXP", .value = abi.INTSXP },
    .{ .name = "REALSXP", .expression = "REALSXP", .value = abi.REALSXP },
    .{ .name = "CPLXSXP", .expression = "CPLXSXP", .value = abi.CPLXSXP },
    .{ .name = "STRSXP", .expression = "STRSXP", .value = abi.STRSXP },
    .{ .name = "DOTSXP", .expression = "DOTSXP", .value = abi.DOTSXP },
    .{ .name = "ANYSXP", .expression = "ANYSXP", .value = abi.ANYSXP },
    .{ .name = "VECSXP", .expression = "VECSXP", .value = abi.VECSXP },
    .{ .name = "EXPRSXP", .expression = "EXPRSXP", .value = abi.EXPRSXP },
    .{ .name = "BCODESXP", .expression = "BCODESXP", .value = abi.BCODESXP },
    .{ .name = "EXTPTRSXP", .expression = "EXTPTRSXP", .value = abi.EXTPTRSXP },
    .{ .name = "WEAKREFSXP", .expression = "WEAKREFSXP", .value = abi.WEAKREFSXP },
    .{ .name = "RAWSXP", .expression = "RAWSXP", .value = abi.RAWSXP },
    .{ .name = "OBJSXP", .expression = "OBJSXP", .value = abi.OBJSXP },
    .{ .name = "S4SXP", .expression = "S4SXP", .value = abi.S4SXP },
    .{ .name = "NEWSXP", .expression = "NEWSXP", .value = abi.NEWSXP },
    .{ .name = "FREESXP", .expression = "FREESXP", .value = abi.FREESXP },
    .{ .name = "FUNSXP", .expression = "FUNSXP", .value = abi.FUNSXP },
    .{ .name = "CE_NATIVE", .expression = "CE_NATIVE", .value = abi.CE_NATIVE },
    .{ .name = "CE_UTF8", .expression = "CE_UTF8", .value = abi.CE_UTF8 },
    .{ .name = "CE_LATIN1", .expression = "CE_LATIN1", .value = abi.CE_LATIN1 },
    .{ .name = "CE_BYTES", .expression = "CE_BYTES", .value = abi.CE_BYTES },
    .{ .name = "CE_SYMBOL", .expression = "CE_SYMBOL", .value = abi.CE_SYMBOL },
    .{ .name = "CE_ANY", .expression = "CE_ANY", .value = abi.CE_ANY },
    .{ .name = "FALSE", .expression = "FALSE", .value = abi.FALSE },
    .{ .name = "TRUE", .expression = "TRUE", .value = abi.TRUE },
    // R exposes both NA macros through the runtime variable R_NaInt. Its public
    // contract fixes that value to INT_MIN, which remains a constant expression.
    .{ .name = "NA_INTEGER", .expression = "INT_MIN", .value = abi.NA_INTEGER },
    .{ .name = "NA_LOGICAL", .expression = "INT_MIN", .value = abi.NA_LOGICAL },
};

const header =
    \\/* Generated by src/c/check.zig. Do not edit. */
    \\#include <limits.h>
    \\#include <stddef.h>
    \\#if defined(__clang__)
    \\# pragma clang diagnostic push
    \\# pragma clang diagnostic ignored "-Wunknown-warning-option"
    \\#endif
    \\#if defined(__GNUC__) && !defined(__clang__)
    \\# pragma GCC diagnostic push
    \\# pragma GCC diagnostic ignored "-Wpedantic"
    \\#endif
    \\#include <Rinternals.h>
    \\#include <R_ext/Arith.h>
    \\#include <R_ext/Boolean.h>
    \\#include <R_ext/Random.h>
    \\#include <R_ext/Rdynload.h>
    \\#include <Rmath.h>
    \\#if defined(__clang__)
    \\# pragma clang diagnostic pop
    \\#endif
    \\#if defined(__GNUC__) && !defined(__clang__)
    \\# pragma GCC diagnostic pop
    \\#endif
    \\
    \\_Static_assert(sizeof(SEXP) == sizeof(void *), "RZig SEXP pointer width mismatch");
    \\_Static_assert(sizeof(SEXPTYPE) == sizeof(unsigned int), "RZig SEXPTYPE width mismatch");
    \\_Static_assert(sizeof(R_xlen_t) == sizeof(ptrdiff_t), "RZig R_xlen_t width mismatch");
    \\_Static_assert(sizeof(Rboolean) == sizeof(int), "RZig Rboolean width mismatch");
    \\_Static_assert(sizeof(Rbyte) == sizeof(unsigned char), "RZig Rbyte width mismatch");
    \\
;

/// Render the portable C source used by both the repository and fixture.
pub fn render(b: *std.Build) []const u8 {
    const allocator = b.allocator;
    var output: std.ArrayList(u8) = .empty;
    output.appendSlice(allocator, header) catch @panic("out of memory while generating ABI checks");

    for (constants) |constant| {
        const line = b.fmt(
            "_Static_assert((long long)({s}) == {d}LL, \"RZig {s} value mismatch\");\n",
            .{ constant.expression, constant.value, constant.name },
        );
        output.appendSlice(allocator, line) catch @panic("out of memory while generating ABI checks");
    }

    return output.toOwnedSlice(allocator) catch @panic("out of memory while generating ABI checks");
}

test "every supported numeric ABI constant has one check" {
    try std.testing.expectEqual(@as(usize, 38), constants.len);
}
