/* Generated by rzig::use_rzig() - do not edit.
 *
 * This file exists for two reasons:
 *   1. $(OBJECTS) must be non-empty for R's SHLIB rule.
 *   2. Referencing rzig_init() forces the linker to keep the archive member
 *      that defines it. Without a reference from a real object file, member
 *      selection or --gc-sections can drop it, and the package then loads with
 *      no registered routines and every .Call fails.
 *
 * R_init_rzigcausal must match the package name EXACTLY.
 *
 * The file includes no R header: some R distributions install the headers
 * without R_ext/Visibility.h, and the two entry points need only the default
 * symbol visibility, which the macro below requests from GCC and Clang.
 */
#if defined(_WIN32) || defined(__CYGWIN__)
#  define RZIG_VISIBLE
#elif defined(__GNUC__) || defined(__clang__)
#  define RZIG_VISIBLE __attribute__((visibility("default")))
#else
#  define RZIG_VISIBLE
#endif

/* DllInfo is opaque. All actual R API declarations are imported by Zig. */
typedef struct _DllInfo DllInfo;

void rzig_init(DllInfo *dll);   /* defined in Zig, see src/register.zig */

void RZIG_VISIBLE R_init_rzigcausal(DllInfo *dll) {
    rzig_init(dll);
}

void RZIG_VISIBLE R_unload_rzigcausal(DllInfo *dll) {
    (void) dll;
}
