/* Generated by rzig::use_rzig() - do not edit.
 *
 * This file exists for two reasons:
 *   1. $(OBJECTS) must be non-empty for R's SHLIB rule.
 *   2. Referencing rzig_init() forces the linker to keep the archive member
 *      that defines it. Without a reference from a real object file, member
 *      selection or --gc-sections can drop it, and the package then loads with
 *      no registered routines and every .Call fails.
 *
 * R_init_rzigcausal must match the package name EXACTLY.
 */
#include <R_ext/Visibility.h>

/* DllInfo is opaque. All actual R API declarations are imported by Zig. */
typedef struct _DllInfo DllInfo;

void rzig_init(DllInfo *dll);   /* defined in Zig, see src/register.zig */

void attribute_visible R_init_rzigcausal(DllInfo *dll) {
    rzig_init(dll);
}

void attribute_visible R_unload_rzigcausal(DllInfo *dll) {
    (void) dll;
}
