/* Generated by rzig::use_rzig() - do not edit.
 *
 * This file exists for two reasons:
 *   1. $(OBJECTS) must be non-empty for R's SHLIB rule.
 *   2. Referencing rzig_init() forces the linker to keep the archive member
 *      that defines it. Without a reference from a real object file, member
 *      selection or --gc-sections can drop it, and the package then loads with
 *      no registered routines and every .Call fails.
 *
 * R_init_@PKG@ must match the package name EXACTLY.
 */
#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

void rzig_init(DllInfo *dll);   /* defined in Zig, see src/register.zig */

void R_init_@PKG@(DllInfo *dll) {
    rzig_init(dll);
}

void R_unload_@PKG@(DllInfo *dll) {
    (void) dll;
}
