/* Generated by src/c/check.zig. Do not edit. */
#include <limits.h>
#include <stddef.h>
#if defined(__clang__)
# pragma clang diagnostic push
# pragma clang diagnostic ignored "-Wunknown-warning-option"
#endif
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wpedantic"
#endif
#include <Rinternals.h>
#include <R_ext/Arith.h>
#include <R_ext/Boolean.h>
#include <R_ext/Random.h>
#include <R_ext/Rdynload.h>
#include <Rmath.h>
#if defined(__clang__)
# pragma clang diagnostic pop
#endif
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC diagnostic pop
#endif

_Static_assert(sizeof(SEXP) == sizeof(void *), "RZig SEXP pointer width mismatch");
_Static_assert(sizeof(SEXPTYPE) == sizeof(unsigned int), "RZig SEXPTYPE width mismatch");
_Static_assert(sizeof(R_xlen_t) == sizeof(ptrdiff_t), "RZig R_xlen_t width mismatch");
_Static_assert(sizeof(Rboolean) == sizeof(int), "RZig Rboolean width mismatch");
_Static_assert(sizeof(Rbyte) == sizeof(unsigned char), "RZig Rbyte width mismatch");
_Static_assert((long long)(NILSXP) == 0LL, "RZig NILSXP value mismatch");
_Static_assert((long long)(SYMSXP) == 1LL, "RZig SYMSXP value mismatch");
_Static_assert((long long)(LISTSXP) == 2LL, "RZig LISTSXP value mismatch");
_Static_assert((long long)(CLOSXP) == 3LL, "RZig CLOSXP value mismatch");
_Static_assert((long long)(ENVSXP) == 4LL, "RZig ENVSXP value mismatch");
_Static_assert((long long)(PROMSXP) == 5LL, "RZig PROMSXP value mismatch");
_Static_assert((long long)(LANGSXP) == 6LL, "RZig LANGSXP value mismatch");
_Static_assert((long long)(SPECIALSXP) == 7LL, "RZig SPECIALSXP value mismatch");
_Static_assert((long long)(BUILTINSXP) == 8LL, "RZig BUILTINSXP value mismatch");
_Static_assert((long long)(CHARSXP) == 9LL, "RZig CHARSXP value mismatch");
_Static_assert((long long)(LGLSXP) == 10LL, "RZig LGLSXP value mismatch");
_Static_assert((long long)(INTSXP) == 13LL, "RZig INTSXP value mismatch");
_Static_assert((long long)(REALSXP) == 14LL, "RZig REALSXP value mismatch");
_Static_assert((long long)(CPLXSXP) == 15LL, "RZig CPLXSXP value mismatch");
_Static_assert((long long)(STRSXP) == 16LL, "RZig STRSXP value mismatch");
_Static_assert((long long)(DOTSXP) == 17LL, "RZig DOTSXP value mismatch");
_Static_assert((long long)(ANYSXP) == 18LL, "RZig ANYSXP value mismatch");
_Static_assert((long long)(VECSXP) == 19LL, "RZig VECSXP value mismatch");
_Static_assert((long long)(EXPRSXP) == 20LL, "RZig EXPRSXP value mismatch");
_Static_assert((long long)(BCODESXP) == 21LL, "RZig BCODESXP value mismatch");
_Static_assert((long long)(EXTPTRSXP) == 22LL, "RZig EXTPTRSXP value mismatch");
_Static_assert((long long)(WEAKREFSXP) == 23LL, "RZig WEAKREFSXP value mismatch");
_Static_assert((long long)(RAWSXP) == 24LL, "RZig RAWSXP value mismatch");
_Static_assert((long long)(OBJSXP) == 25LL, "RZig OBJSXP value mismatch");
_Static_assert((long long)(S4SXP) == 25LL, "RZig S4SXP value mismatch");
_Static_assert((long long)(NEWSXP) == 30LL, "RZig NEWSXP value mismatch");
_Static_assert((long long)(FREESXP) == 31LL, "RZig FREESXP value mismatch");
_Static_assert((long long)(FUNSXP) == 99LL, "RZig FUNSXP value mismatch");
_Static_assert((long long)(CE_NATIVE) == 0LL, "RZig CE_NATIVE value mismatch");
_Static_assert((long long)(CE_UTF8) == 1LL, "RZig CE_UTF8 value mismatch");
_Static_assert((long long)(CE_LATIN1) == 2LL, "RZig CE_LATIN1 value mismatch");
_Static_assert((long long)(CE_BYTES) == 3LL, "RZig CE_BYTES value mismatch");
_Static_assert((long long)(CE_SYMBOL) == 5LL, "RZig CE_SYMBOL value mismatch");
_Static_assert((long long)(CE_ANY) == 99LL, "RZig CE_ANY value mismatch");
_Static_assert((long long)(FALSE) == 0LL, "RZig FALSE value mismatch");
_Static_assert((long long)(TRUE) == 1LL, "RZig TRUE value mismatch");
_Static_assert((long long)(INT_MIN) == -2147483648LL, "RZig NA_INTEGER value mismatch");
_Static_assert((long long)(INT_MIN) == -2147483648LL, "RZig NA_LOGICAL value mismatch");
