package_dir <- tempfile("rzhello-")
dir.create(package_dir)
dir.create(file.path(package_dir, "R"))

writeLines(
  c(
    "Package: rzhello",
    "Type: Package",
    "Title: RZig Scaffold Test",
    "Version: 0.0.1",
    "Authors@R: person('Test', 'Author', email = 'test@example.org', role = c('aut', 'cre'))",
    "Description: Verifies that use_rzig creates an installable Zig-backed package.",
    "License: MIT",
    "Encoding: UTF-8"
  ),
  file.path(package_dir, "DESCRIPTION")
)
writeLines(character(), file.path(package_dir, "NAMESPACE"))

rzig::use_rzig(package_dir)

original_zig <- Sys.getenv("ZIG", unset = NA_character_)
old_zig <- file.path(tempdir(), "old Zig compiler")
writeLines(
  c(
    "#!/bin/sh",
    "if test \"${1:-}\" = version; then",
    "  printf '%s\\n' '0.15.2'",
    "  exit 0",
    "fi",
    "exit 99"
  ),
  old_zig
)
Sys.chmod(old_zig, mode = "0755")
Sys.setenv(ZIG = old_zig)
version_error <- tryCatch(
  rzig::document(package_dir),
  error = identity
)
if (is.na(original_zig)) {
  Sys.unsetenv("ZIG")
} else {
  Sys.setenv(ZIG = original_zig)
}
stopifnot(
  inherits(version_error, "error"),
  grepl("Zig 0.15.2 found", conditionMessage(version_error), fixed = TRUE),
  grepl("0.16.0 or newer is required", conditionMessage(version_error), fixed = TRUE)
)

expected <- c(
  "configure",
  "configure.win",
  "cleanup",
  "cleanup.win",
  "src/entry.c",
  "src/Makevars.in",
  "src/Makevars.win.in",
  "src/rzig/build.zig",
  "src/rzig/build.zig.zon",
  "src/rzig/src/main.zig",
  "src/rzig/framework/rzig.zig",
  "src/rzig/framework/generated/manifest.zig",
  "R/rzig-wrappers.R"
)
missing <- expected[!file.exists(file.path(package_dir, expected))]
if (length(missing)) {
  stop("use_rzig did not create: ", paste(missing, collapse = ", "))
}
if (.Platform$OS.type != "windows") {
  stopifnot(
    file.access(file.path(package_dir, "cleanup"), mode = 1L) == 0L,
    file.access(file.path(package_dir, "cleanup.win"), mode = 1L) == 0L
  )
}

namespace <- readLines(file.path(package_dir, "NAMESPACE"), warn = FALSE)
stopifnot(
  any(grepl("useDynLib\\(\"rzhello\"", namespace)),
  '  hello_zig_ = "hello_zig"' %in% namespace,
  'export("hello_zig")' %in% namespace
)

wrapper_path <- file.path(package_dir, "R", "rzig-wrappers.R")
wrapper <- readLines(wrapper_path, warn = FALSE)
stopifnot(
  "#' Return a friendly greeting." %in% wrapper,
  "#' @param name A value passed to the Zig implementation." %in% wrapper,
  "#' @return The value returned by the Zig implementation." %in% wrapper,
  "#' @export" %in% wrapper,
  "hello_zig <- function(name) {" %in% wrapper,
  "  .Call(hello_zig_, name)" %in% wrapper
)

writeLines(
  c(
    "#' Existing R helper.",
    "#' @export",
    "existing_helper <- function() TRUE"
  ),
  file.path(package_dir, "R", "existing-helper.R")
)
write("export(existing_helper)", file.path(package_dir, "NAMESPACE"), append = TRUE)

main_path <- file.path(package_dir, "src", "rzig", "src", "main.zig")
main <- readLines(main_path, warn = FALSE)
addition <- c(
  "",
  "/// Add two scalar values.",
  "/// @export",
  "pub fn add_values(left: f64, right: f64) f64 {",
  "    return left + right;",
  "}",
  ""
)
location <- grep("^comptime \\{", main)[1L]
main <- append(main, addition, after = location - 1L)
writeLines(main, main_path, useBytes = TRUE)

rzig::document(package_dir)
documented_wrapper <- readLines(wrapper_path, warn = FALSE)
documented_namespace <- readLines(
  file.path(package_dir, "NAMESPACE"),
  warn = FALSE
)
stopifnot(
  "#' Add two scalar values." %in% documented_wrapper,
  "#' @param left A value passed to the Zig implementation." %in% documented_wrapper,
  "#' @param right A value passed to the Zig implementation." %in% documented_wrapper,
  "add_values <- function(left, right) {" %in% documented_wrapper,
  "  .Call(add_values_, left, right)" %in% documented_wrapper,
  '  add_values_ = "add_values"' %in% documented_namespace,
  'export("add_values")' %in% documented_namespace,
  "export(existing_helper)" %in% documented_namespace,
  sum(grepl("Generated by rzig::document\\(\\): begin", documented_namespace)) == 1L,
  !any(grepl("\\.fixes", documented_namespace))
)

rzig::document(package_dir)
stopifnot(
  identical(documented_wrapper, readLines(wrapper_path, warn = FALSE)),
  identical(
    documented_namespace,
    readLines(file.path(package_dir, "NAMESPACE"), warn = FALSE)
  )
)

# Simulate a roxygen2 NAMESPACE rewrite, then verify the documented final
# rzig::document() call restores native registration without losing R exports.
writeLines(
  c("export(existing_helper)", "export(hello_zig)", "export(add_values)"),
  file.path(package_dir, "NAMESPACE")
)
rzig::document(package_dir)
roxygen_namespace <- readLines(
  file.path(package_dir, "NAMESPACE"),
  warn = FALSE
)
if (!any(grepl("hello_zig_", roxygen_namespace, fixed = TRUE))) {
  stop(
    "RZig registration was not restored after the simulated roxygen2 rewrite:\n",
    paste(roxygen_namespace, collapse = "\n")
  )
}
stopifnot(
  "export(existing_helper)" %in% roxygen_namespace,
  any(grepl('hello_zig_ = "hello_zig"', roxygen_namespace, fixed = TRUE)),
  any(grepl('add_values_ = "add_values"', roxygen_namespace, fixed = TRUE)),
  'export("hello_zig")' %in% roxygen_namespace,
  'export("add_values")' %in% roxygen_namespace,
  !"export(hello_zig)" %in% roxygen_namespace,
  !"export(add_values)" %in% roxygen_namespace,
  sum(grepl("Generated by rzig::document\\(\\): begin", roxygen_namespace)) == 1L
)

if (requireNamespace("roxygen2", quietly = TRUE)) {
  writeLines(
    c("# Generated by roxygen2: do not edit by hand", "", roxygen_namespace),
    file.path(package_dir, "NAMESPACE")
  )
  suppressMessages(roxygen2::roxygenise(package_dir))
  rzig::document(package_dir)
  actual_roxygen_namespace <- readLines(
    file.path(package_dir, "NAMESPACE"),
    warn = FALSE
  )
  stopifnot(
    actual_roxygen_namespace[[1L]] ==
      "# Generated by roxygen2: do not edit by hand",
    "export(existing_helper)" %in% actual_roxygen_namespace,
    any(grepl(
      'hello_zig_ = "hello_zig"',
      actual_roxygen_namespace,
      fixed = TRUE
    )),
    any(grepl(
      'add_values_ = "add_values"',
      actual_roxygen_namespace,
      fixed = TRUE
    )),
    sum(grepl(
      "Generated by rzig::document\\(\\): begin",
      actual_roxygen_namespace
    )) == 1L
  )
}

install_library <- tempfile("rzhello-library-")
dir.create(install_library)
status <- system2(
  file.path(R.home("bin"), "R"),
  c("CMD", "INSTALL", paste0("--library=", install_library), package_dir)
)
if (!identical(status, 0L)) {
  stop("the scaffolded package failed to install with status ", status)
}

.libPaths(c(install_library, .libPaths()))
if ("rzhello" %in% loadedNamespaces()) {
  unloadNamespace("rzhello")
}
loadNamespace("rzhello")
result <- getExportedValue("rzhello", "hello_zig")("Zig")
stopifnot(identical(result, "Hello, Zig!"))
sum_result <- getExportedValue("rzhello", "add_values")(1.25, 2.75)
stopifnot(identical(sum_result, 4))

message("use_rzig and document workflows OK")
