//! Emits src/generated/arity.zig - one wrapper struct per arity 0..32.
//!
//! Why generated source rather than comptime: Zig can build function *types*
//! with @Type but not function *bodies*, so a wrapper whose parameter count is
//! comptime-computed cannot be written directly.
//!
//! Run with `zig build gen`. Commit the output.

const std = @import("std");

const MAX_ARITY = 32;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    const args = try std.process.argsAlloc(alloc);
    defer std.process.argsFree(alloc, args);
    if (args.len < 2) return error.MissingOutputPath;

    var out = std.ArrayList(u8).init(alloc);
    defer out.deinit();
    const w = out.writer();

    try w.writeAll(
        \\//! GENERATED by tools/gen_wrappers.zig - do not edit.
        \\//! Regenerate with `zig build gen`.
        \\
        \\const c = @import("../c/abi.zig");
        \\const boundary = @import("../boundary.zig");
        \\
        \\
    );

    var n: usize = 0;
    while (n <= MAX_ARITY) : (n += 1) {
        try w.print(
            \\pub fn Arity{d}(comptime func: anytype, comptime name: []const u8) type {{
            \\    return struct {{
            \\        pub fn call(
        , .{n});
        var i: usize = 0;
        while (i < n) : (i += 1) {
            try w.print("a{d}: c.SEXP, ", .{i});
        }
        try w.writeAll(
            \\) callconv(.c) c.SEXP {
            \\            return boundary.invoke(func, name, .{
        );
        i = 0;
        while (i < n) : (i += 1) {
            try w.print(" a{d},", .{i});
        }
        try w.writeAll(
            \\ });
            \\        }
            \\    };
            \\}
            \\
            \\
        );
    }

    var file = try std.fs.cwd().createFile(args[1], .{});
    defer file.close();
    try file.writeAll(out.items);
    std.debug.print("wrote {s} ({d} arities)\n", .{ args[1], MAX_ARITY + 1 });
}
