//! Emits src/generated/arity.zig - one wrapper struct per arity 0..32.
//!
//! Why generated source rather than comptime: Zig can build function *types*
//! with @Type but not function *bodies*, so a wrapper whose parameter count is
//! comptime-computed cannot be written directly.
//!
//! Run with `zig build gen`. Commit the output.

const std = @import("std");

const MAX_ARITY = 32;

pub fn main(init: std.process.Init) !void {
    var args = try std.process.Args.iterateAllocator(init.minimal.args, init.gpa);
    defer args.deinit();
    _ = args.next();
    const output_path = args.next() orelse return error.MissingOutputPath;

    const source = try render(init.gpa);
    defer init.gpa.free(source);
    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = output_path, .data = source });
}

fn render(allocator: std.mem.Allocator) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(allocator);

    try out.appendSlice(allocator,
        \\//! GENERATED by tools/gen_wrappers.zig - do not edit.
        \\//! Regenerate with `zig build gen`.
        \\
        \\const c = @import("../c/abi.zig");
        \\const boundary = @import("../boundary.zig");
        \\
        \\
    );

    var n: usize = 0;
    while (n <= MAX_ARITY) : (n += 1) {
        try out.print(allocator,
            \\/// Build a C-ABI wrapper for a function with {d} R-visible arguments.
            \\pub fn Arity{d}(comptime func: anytype, comptime name: []const u8) type {{
            \\    return struct {{
            \\        pub fn call(
        , .{ n, n });
        var i: usize = 0;
        while (i < n) : (i += 1) {
            if (i > 0) try out.appendSlice(allocator, ", ");
            try out.print(allocator, "a{d}: c.SEXP", .{i});
        }
        try out.appendSlice(allocator,
            \\) callconv(.c) c.SEXP {
            \\            return boundary.invoke(func, name, .{
        );
        i = 0;
        while (i < n) : (i += 1) {
            if (i > 0) try out.appendSlice(allocator, ",");
            try out.print(allocator, " a{d}", .{i});
        }
        try out.appendSlice(allocator,
            \\ });
            \\        }
            \\    };
            \\}
            \\
            \\
        );
    }

    return out.toOwnedSlice(allocator);
}

test "generator emits every supported arity exactly once" {
    const source = try render(std.testing.allocator);
    defer std.testing.allocator.free(source);

    try std.testing.expectEqual(@as(usize, MAX_ARITY + 1), std.mem.count(u8, source, "pub fn Arity"));
    try std.testing.expect(std.mem.indexOf(u8, source, "pub fn Arity0(") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "pub fn Arity32(") != null);
    try std.testing.expect(std.mem.indexOf(u8, source, "pub fn Arity33(") == null);
}
