//! Finds public Zig functions marked with `/// @export` and emits a manifest.

const std = @import("std");

const max_source_bytes = 16 * 1024 * 1024;

pub fn main(init: std.process.Init) !void {
    var args = try std.process.Args.iterateAllocator(init.minimal.args, init.gpa);
    defer args.deinit();
    _ = args.next();
    const input_path = args.next() orelse return error.MissingInputPath;
    const output_path = args.next() orelse return error.MissingOutputPath;

    const source = try std.Io.Dir.cwd().readFileAllocOptions(
        init.io,
        input_path,
        init.gpa,
        .limited(max_source_bytes),
        .of(u8),
        0,
    );
    defer init.gpa.free(source);

    const manifest = try renderManifest(init.gpa, source);
    defer init.gpa.free(manifest);
    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = output_path, .data = manifest });
}

fn renderManifest(allocator: std.mem.Allocator, source: [:0]const u8) ![]u8 {
    var tree = try std.zig.Ast.parse(allocator, source, .zig);
    defer tree.deinit(allocator);
    if (tree.errors.len != 0) return error.InvalidZigSource;

    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(allocator);
    try out.appendSlice(allocator,
        \\//! GENERATED by tools/scan.zig - do not edit.
        \\//! Regenerate with `zig build gen`.
        \\
        \\/// Bind exported function names to the package's root Zig module.
        \\pub fn Bind(comptime root: type) type {
        \\    return struct {
        \\        const bound_root = root;
        \\
        \\        /// Metadata for public functions exposed through RZig.
        \\        pub const exports = .{
        \\
    );

    for (tree.rootDecls()) |decl| {
        var buffer: [1]std.zig.Ast.Node.Index = undefined;
        const proto = tree.fullFnProto(&buffer, decl) orelse continue;
        if (proto.visib_token == null) continue;
        const name_token = proto.name_token orelse continue;
        const doc_start = firstDocToken(&tree, proto.firstToken()) orelse continue;
        const doc_end = proto.firstToken() - 1;
        if (!hasExportMarker(&tree, doc_start, doc_end)) continue;

        const identifier = tree.tokenSlice(name_token);
        const display_name = try identifierName(allocator, identifier);
        defer if (display_name.owned) |owned| allocator.free(owned);

        var doc: std.ArrayList(u8) = .empty;
        defer doc.deinit(allocator);
        try collectDocumentation(allocator, &doc, &tree, doc_start, doc_end);

        try out.print(allocator,
            \\            .{{
            \\                .name = "{f}",
            \\                .func = bound_root.{s},
            \\                .doc = "{f}",
            \\            }},
            \\
        , .{
            std.zig.fmtString(display_name.bytes),
            identifier,
            std.zig.fmtString(doc.items),
        });
    }

    try out.appendSlice(allocator,
        \\        };
        \\    };
        \\}
        \\
    );
    return out.toOwnedSlice(allocator);
}

fn firstDocToken(tree: *const std.zig.Ast, declaration_first: std.zig.Ast.TokenIndex) ?std.zig.Ast.TokenIndex {
    if (declaration_first == 0) return null;
    var token = declaration_first - 1;
    if (tree.tokenTag(token) != .doc_comment) return null;
    while (token > 0 and tree.tokenTag(token - 1) == .doc_comment) token -= 1;
    return token;
}

fn hasExportMarker(
    tree: *const std.zig.Ast,
    start: std.zig.Ast.TokenIndex,
    end: std.zig.Ast.TokenIndex,
) bool {
    var token = start;
    while (token <= end) : (token += 1) {
        if (std.mem.eql(u8, std.mem.trim(u8, docBody(tree.tokenSlice(token)), " \t\r"), "@export")) {
            return true;
        }
    }
    return false;
}

fn collectDocumentation(
    allocator: std.mem.Allocator,
    out: *std.ArrayList(u8),
    tree: *const std.zig.Ast,
    start: std.zig.Ast.TokenIndex,
    end: std.zig.Ast.TokenIndex,
) !void {
    var wrote_line = false;
    var token = start;
    while (token <= end) : (token += 1) {
        const line = docBody(tree.tokenSlice(token));
        if (std.mem.eql(u8, std.mem.trim(u8, line, " \t\r"), "@export")) continue;
        if (wrote_line) try out.append(allocator, '\n');
        try out.appendSlice(allocator, line);
        wrote_line = true;
    }
}

fn docBody(token: []const u8) []const u8 {
    const body = token[3..];
    return if (body.len > 0 and body[0] == ' ') body[1..] else body;
}

const IdentifierName = struct {
    bytes: []const u8,
    owned: ?[]u8 = null,
};

fn identifierName(allocator: std.mem.Allocator, token: []const u8) !IdentifierName {
    if (std.mem.startsWith(u8, token, "@\"") and std.mem.endsWith(u8, token, "\"")) {
        const parsed = try std.zig.string_literal.parseAlloc(allocator, token[1..]);
        return .{ .bytes = parsed, .owned = parsed };
    }
    return .{ .bytes = token };
}

test "manifest contains only marked public functions and preserves documentation" {
    const source: [:0]const u8 =
        \\/// Add "values".
        \\/// Preserves \ paths.
        \\/// @export
        \\pub fn add_values(a: f64, b: f64) f64 {
        \\    return a + b;
        \\}
        \\
        \\/// @export
        \\fn private_helper() void {}
        \\
        \\/// Ordinary public helper.
        \\pub fn helper() void {}
        \\
    ;

    const manifest = try renderManifest(std.testing.allocator, source);
    defer std.testing.allocator.free(manifest);

    try std.testing.expect(std.mem.indexOf(u8, manifest, "pub fn Bind(comptime root: type) type") != null);
    try std.testing.expect(std.mem.indexOf(u8, manifest, ".name = \"add_values\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, manifest, ".func = bound_root.add_values") != null);
    try std.testing.expect(std.mem.indexOf(u8, manifest, ".doc = \"Add \\\"values\\\".\\nPreserves \\\\ paths.\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, manifest, "private_helper") == null);
    try std.testing.expect(std.mem.indexOf(u8, manifest, "bound_root.helper") == null);
}

test "manifest supports marker-only docs and quoted identifiers" {
    const source: [:0]const u8 =
        \\/// @export
        \\pub fn @"r-name"() void {}
        \\
    ;

    const manifest = try renderManifest(std.testing.allocator, source);
    defer std.testing.allocator.free(manifest);

    try std.testing.expect(std.mem.indexOf(u8, manifest, ".name = \"r-name\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, manifest, ".func = bound_root.@\"r-name\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, manifest, ".doc = \"\"") != null);
}

test "invalid Zig source is rejected" {
    try std.testing.expectError(
        error.InvalidZigSource,
        renderManifest(std.testing.allocator, "pub fn broken(\x00"),
    );
}
