#' Render the generated bindings for a set of exported functions
#'
#' Produces the three texts that [document()] writes into a package, without
#' writing anything: the Zig manifest that registers the exported functions,
#' the R wrappers that call them, and the `NAMESPACE` block that resolves the
#' native symbols. Use the function to inspect what [document()] will
#' generate.
#'
#' @param exports An object returned by [scan_exports()].
#' @param package The package name; by default taken from `exports`.
#'
#' @return An object of class `rzig_bindings`: a list with the character
#'   strings `manifest` (`src/rzig/framework/generated/manifest.zig`),
#'   `wrappers` (`R/rzig-wrappers.R`) and `namespace` (the generated
#'   `NAMESPACE` block), and the `exports` the texts were rendered from.
#' @examples
#' package_path <- tempfile("rzig-render-", tmpdir = tempdir())
#' dir.create(package_path)
#' writeLines(c("Package: examplepkg", "Version: 0.0.1"),
#'   file.path(package_path, "DESCRIPTION"))
#' use_rzig(package_path)
#' bindings <- render_bindings(scan_exports(package_path))
#' cat(bindings$wrappers)
#' cat(bindings$namespace)
#' unlink(package_path, recursive = TRUE)
#' @export
render_bindings <- function(exports, package = attr(exports, "package", exact = TRUE)) {
  if (!inherits(exports, "rzig_exports")) {
    stop("`exports` must be the result of scan_exports()", call. = FALSE)
  }
  if (is.null(package) || length(package) != 1L || !grepl("^[A-Za-z][A-Za-z0-9.]*$", package)) {
    stop("`package` must be a valid R package name", call. = FALSE)
  }
  aliases <- .rzig_native_aliases(exports)
  result <- list(
    manifest = .rzig_render_manifest(exports),
    wrappers = .rzig_render_wrappers(exports, aliases),
    namespace = .rzig_render_namespace(exports, aliases, package),
    exports = exports
  )
  structure(result, class = "rzig_bindings", package = package)
}

#' @export
print.rzig_bindings <- function(x, ...) {
  package <- attr(x, "package", exact = TRUE)
  cat(sprintf(
    "Generated bindings for package %s: %d exported function%s\n",
    package, length(x$exports), if (length(x$exports) == 1L) "" else "s"
  ))
  if (!is.null(x$files)) {
    cat("Files written:\n")
    for (file in x$files) cat("  ", file, "\n", sep = "")
  }
  cat("\n-- R/rzig-wrappers.R --\n")
  cat(x$wrappers)
  cat("\n-- NAMESPACE block --\n")
  cat(x$namespace)
  cat("\n-- src/rzig/framework/generated/manifest.zig --\n")
  cat(x$manifest)
  invisible(x)
}

.rzig_render_manifest <- function(exports) {
  header <- paste0(
    "//! GENERATED by tools/scan.zig - do not edit.\n",
    "//! Regenerate with `zig build gen` or `rzig::document()`.\n",
    "\n",
    "/// Bind exported function names to the package's root Zig module.\n",
    "pub fn Bind(comptime root: type) type {\n",
    "    return struct {\n",
    "        const bound_root = root;\n",
    "\n",
    "        /// Metadata for public functions exposed through RZig.\n"
  )
  if (!length(exports)) {
    return(paste0(header, "        pub const exports = .{};\n    };\n}\n"))
  }
  entries <- vapply(exports, function(item) {
    quoted <- vapply(item$parameters, .rzig_zig_string, character(1L))
    list_text <- if (length(quoted) == 0L) {
      ".{}"
    } else if (length(quoted) == 1L) {
      paste0(".{", quoted, "}")
    } else {
      paste0(".{ ", paste(quoted, collapse = ", "), " }")
    }
    paste0(
      "            .{\n",
      "                .name = ", .rzig_zig_string(item$name), ",\n",
      "                .func = bound_root.", item$identifier, ",\n",
      "                .doc = ", .rzig_zig_string(item$doc), ",\n",
      "                .parameters = ", list_text, ",\n",
      "            },\n"
    )
  }, character(1L))
  paste0(
    header,
    "        pub const exports = .{\n",
    paste(entries, collapse = ""),
    "        };\n",
    "    };\n",
    "}\n"
  )
}

.rzig_zig_string <- function(value) {
  bytes <- charToRaw(value)
  pieces <- vapply(as.integer(bytes), function(byte) {
    if (byte == 0x22L) return("\\\"")
    if (byte == 0x5cL) return("\\\\")
    if (byte == 0x0aL) return("\\n")
    if (byte == 0x0dL) return("\\r")
    if (byte == 0x09L) return("\\t")
    if (byte >= 0x20L && byte <= 0x7eL) return(rawToChar(as.raw(byte)))
    sprintf("\\x%02x", byte)
  }, character(1L))
  paste0("\"", paste(pieces, collapse = ""), "\"")
}

.rzig_r_string <- function(value) {
  bytes <- as.integer(charToRaw(value))
  unsupported <- bytes %in% c(0:8, 11L, 12L, 14:31, 127L)
  if (any(unsupported)) {
    stop("a generated R string contains a control character", call. = FALSE)
  }
  pieces <- vapply(bytes, function(byte) {
    if (byte == 0x22L) return("\\\"")
    if (byte == 0x5cL) return("\\\\")
    if (byte == 0x0aL) return("\\n")
    if (byte == 0x0dL) return("\\r")
    if (byte == 0x09L) return("\\t")
    rawToChar(as.raw(byte))
  }, character(1L))
  out <- paste0("\"", paste(pieces, collapse = ""), "\"")
  Encoding(out) <- "unknown"
  out
}

.rzig_reserved_words <- c(
  "if", "else", "repeat", "while", "function", "for", "in", "next", "break",
  "TRUE", "FALSE", "NULL", "Inf", "NaN", "NA", "NA_integer_", "NA_real_",
  "NA_complex_", "NA_character_"
)

.rzig_is_syntactic <- function(name) {
  nzchar(name) &&
    grepl("^([A-Za-z]|\\.(?![0-9]))[A-Za-z0-9._]*$", name, perl = TRUE, useBytes = TRUE)
}

.rzig_r_identifier <- function(name) {
  if (.rzig_is_syntactic(name) && !name %in% .rzig_reserved_words) {
    return(name)
  }
  escaped <- gsub("([\\\\`])", "\\\\\\1", name, perl = TRUE, useBytes = TRUE)
  paste0("`", escaped, "`")
}

.rzig_native_aliases <- function(exports) {
  names <- vapply(exports, function(item) item$name, character(1L))
  vapply(seq_along(exports), function(index) {
    preferred <- paste0(names[[index]], "_")
    if (.rzig_is_syntactic(preferred) && !preferred %in% names) {
      return(preferred)
    }
    ordinal <- index
    repeat {
      fallback <- sprintf(".rzig_symbol_%d", ordinal)
      if (!fallback %in% names) return(fallback)
      ordinal <- ordinal + length(exports) + 1L
    }
  }, character(1L))
}

.rzig_render_wrappers <- function(exports, aliases) {
  out <- "# Generated by rzig::document(). Do not edit.\n"
  for (index in seq_along(exports)) {
    item <- exports[[index]]
    arguments <- vapply(item$parameters, .rzig_r_identifier, character(1L))
    out <- paste0(
      out, "\n",
      .rzig_roxygen_block(item),
      .rzig_r_identifier(item$name), " <- function(", paste(arguments, collapse = ", "),
      ") {\n  .Call(", aliases[[index]],
      paste0(vapply(arguments, function(argument) paste0(", ", argument), character(1L)), collapse = ""),
      ")\n}\n"
    )
  }
  out
}

.rzig_doc_lines <- function(doc) {
  if (!nzchar(doc)) return(character())
  lines <- strsplit(doc, "\n", fixed = TRUE)[[1L]]
  if (grepl("\n$", doc)) lines <- c(lines, "")
  lines
}

.rzig_roxygen_block <- function(item) {
  lines <- .rzig_doc_lines(item$doc)
  trimmed <- trimws(lines, whitespace = "[ \t\r]")
  out <- ""
  first_content <- trimmed[nzchar(trimmed)]
  if (!nzchar(item$doc) || (length(first_content) && substring(first_content[[1L]], 1L, 1L) == "@")) {
    out <- paste0(out, "#' Call ", .rzig_r_identifier(item$name), " in Zig.\n")
  }
  if (nzchar(item$doc)) {
    for (line in lines) {
      out <- paste0(out, "#'", if (nzchar(line)) paste0(" ", line) else "", "\n")
    }
  }
  out <- paste0(out, "#'\n")
  for (parameter in item$parameters) {
    if (.rzig_doc_has_parameter(trimmed, parameter)) next
    out <- paste0(
      out, "#' @param ", .rzig_r_identifier(parameter),
      " A value passed to the Zig implementation.\n"
    )
  }
  if (!.rzig_doc_has_tag(trimmed, "@return")) {
    out <- paste0(out, "#' @return The value returned by the Zig implementation.\n")
  }
  paste0(out, "#' @export\n")
}

.rzig_doc_has_tag <- function(trimmed, tag) {
  for (line in trimmed) {
    if (!startsWith(line, tag)) next
    if (nchar(line, type = "bytes") == nchar(tag, type = "bytes") ||
        grepl("^[[:space:]]", substring(line, nchar(tag, type = "bytes") + 1L), useBytes = TRUE)) {
      return(TRUE)
    }
  }
  FALSE
}

.rzig_doc_has_parameter <- function(trimmed, parameter) {
  for (line in trimmed) {
    if (!startsWith(line, "@param")) next
    rest <- substring(line, 7L)
    if (!grepl("^[[:space:]]", rest, useBytes = TRUE)) next
    declared <- sub("^[ \t]+", "", rest, useBytes = TRUE)
    if (.rzig_parameter_matches(declared, parameter)) return(TRUE)
  }
  FALSE
}

.rzig_parameter_matches <- function(declared, parameter) {
  width <- nchar(parameter, type = "bytes")
  if (startsWith(declared, parameter)) {
    rest <- substring(declared, width + 1L)
    if (!nzchar(rest) || grepl("^[[:space:]]", rest, useBytes = TRUE)) return(TRUE)
  }
  if (startsWith(declared, paste0("`", parameter, "`"))) {
    rest <- substring(declared, width + 3L)
    if (!nzchar(rest) || grepl("^[[:space:]]", rest, useBytes = TRUE)) return(TRUE)
  }
  FALSE
}

.rzig_render_namespace <- function(exports, aliases, package) {
  out <- paste0("# Generated by rzig::document(): begin\nuseDynLib(", .rzig_r_string(package))
  for (index in seq_along(exports)) {
    out <- paste0(out, ",\n  ", aliases[[index]], " = ", .rzig_r_string(exports[[index]]$name))
  }
  out <- paste0(out, "\n)\n")
  for (item in exports) {
    out <- paste0(out, "export(", .rzig_r_string(item$name), ")\n")
  }
  paste0(out, "# Generated by rzig::document(): end\n")
}
