#' Add RZig to an R package
#'
#' Creates a Zig source tree, portable build files, a generated native entry
#' stub, and a working `hello_zig()` example in an existing R package.
#'
#' @param path Path to the package root.
#' @param overwrite Replace files previously managed by RZig.
#'
#' @return The normalized package path, invisibly.
#' @export
use_rzig <- function(path = ".", overwrite = FALSE) {
  if (length(path) != 1L || is.na(path) || !nzchar(path)) {
    stop("`path` must be one non-empty path", call. = FALSE)
  }
  if (length(overwrite) != 1L || is.na(overwrite)) {
    stop("`overwrite` must be TRUE or FALSE", call. = FALSE)
  }
  overwrite <- isTRUE(overwrite)
  path <- normalizePath(path, winslash = "/", mustWork = TRUE)

  description_path <- file.path(path, "DESCRIPTION")
  if (!file.exists(description_path)) {
    stop("`path` must contain an R package DESCRIPTION file", call. = FALSE)
  }
  description <- read.dcf(description_path)
  if (!"Package" %in% colnames(description)) {
    stop("DESCRIPTION must declare a Package field", call. = FALSE)
  }
  package <- unname(description[1L, "Package"])
  if (!grepl("^[A-Za-z][A-Za-z0-9.]*$", package)) {
    stop("unsupported R package name: ", package, call. = FALSE)
  }

  zig_assets <- system.file("zig", package = "rzig")
  templates <- system.file("templates", package = "rzig")
  if (!nzchar(zig_assets) || !nzchar(templates)) {
    stop("the installed rzig package is missing its scaffold assets", call. = FALSE)
  }

  managed <- c(
    "configure",
    "configure.win",
    file.path("src", "entry.c"),
    file.path("src", "Makevars.in"),
    file.path("src", "Makevars.win.in"),
    file.path("src", "rzig"),
    file.path("R", "rzig-wrappers.R")
  )
  conflicts <- managed[file.exists(file.path(path, managed))]
  if (length(conflicts) && !overwrite) {
    stop(
      "RZig-managed files already exist; rerun with `overwrite = TRUE`: ",
      paste(conflicts, collapse = ", "),
      call. = FALSE
    )
  }

  if (overwrite) {
    unlink(file.path(path, "src", "rzig"), recursive = TRUE, force = TRUE)
  }
  dir.create(file.path(path, "src"), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(path, "R"), recursive = TRUE, showWarnings = FALSE)
  .rzig_copy_tree(zig_assets, file.path(path, "src", "rzig"))

  file.copy(
    file.path(templates, "Makevars"),
    file.path(path, "src", "Makevars.in"),
    overwrite = overwrite,
    copy.mode = TRUE
  )
  file.copy(
    file.path(templates, "Makevars.win"),
    file.path(path, "src", "Makevars.win.in"),
    overwrite = overwrite,
    copy.mode = TRUE
  )
  for (script in c("configure", "configure.win")) {
    file.copy(
      file.path(templates, script),
      file.path(path, script),
      overwrite = overwrite,
      copy.mode = TRUE
    )
    Sys.chmod(file.path(path, script), mode = "0755")
  }

  entry <- readLines(file.path(templates, "entry.c"), warn = FALSE)
  entry <- gsub("@PKG@", gsub("[^A-Za-z0-9_]", "_", package), entry, fixed = TRUE)
  writeLines(entry, file.path(path, "src", "entry.c"), useBytes = TRUE)

  wrapper <- c(
    "# Generated by rzig::use_rzig().",
    "",
    "hello_zig <- function(name) {",
    "  .Call(C_hello_zig, name)",
    "}"
  )
  writeLines(wrapper, file.path(path, "R", "rzig-wrappers.R"), useBytes = TRUE)

  namespace_path <- file.path(path, "NAMESPACE")
  namespace <- if (file.exists(namespace_path)) {
    readLines(namespace_path, warn = FALSE)
  } else {
    character()
  }
  namespace <- unique(c(
    namespace,
    sprintf("useDynLib(%s, .registration = TRUE, .fixes = \"C_\")", package),
    "export(hello_zig)"
  ))
  writeLines(namespace, namespace_path, useBytes = TRUE)

  message("Created RZig scaffold in ", path)
  invisible(path)
}

.rzig_copy_tree <- function(source, destination) {
  files <- list.files(
    source,
    all.files = TRUE,
    full.names = TRUE,
    recursive = TRUE,
    include.dirs = FALSE,
    no.. = TRUE
  )
  prefix_length <- nchar(source) + 2L
  relative <- substring(files, prefix_length)
  for (index in seq_along(files)) {
    target <- file.path(destination, relative[index])
    dir.create(dirname(target), recursive = TRUE, showWarnings = FALSE)
    if (!file.copy(files[index], target, overwrite = TRUE, copy.mode = TRUE)) {
      stop("failed to copy RZig asset: ", relative[index], call. = FALSE)
    }
  }
  invisible(destination)
}
