.rzig_managed_files <- c(
  "configure",
  "configure.win",
  "cleanup",
  "cleanup.win",
  file.path("src", "entry.c"),
  file.path("src", "Makevars.in"),
  file.path("src", "Makevars.win.in"),
  file.path("src", "rzig"),
  file.path("R", "rzig-wrappers.R")
)

.rzig_package_info <- function(path) {
  if (length(path) != 1L || is.na(path) || !nzchar(path)) {
    stop("`path` must be one non-empty path", call. = FALSE)
  }
  path <- normalizePath(path, winslash = "/", mustWork = TRUE)
  description_path <- file.path(path, "DESCRIPTION")
  if (!file.exists(description_path)) {
    stop("`path` must contain an R package DESCRIPTION file", call. = FALSE)
  }
  description <- read.dcf(description_path)
  if (!"Package" %in% colnames(description)) {
    stop("DESCRIPTION must declare a Package field", call. = FALSE)
  }
  package <- unname(description[1L, "Package"])
  if (!grepl("^[A-Za-z][A-Za-z0-9.]*$", package)) {
    stop("unsupported R package name: ", package, call. = FALSE)
  }
  list(path = path, package = package)
}

.rzig_source_path <- function(path) {
  file.path(path, "src", "rzig", "src", "main.zig")
}

.rzig_manifest_path <- function(path) {
  file.path(path, "src", "rzig", "framework", "generated", "manifest.zig")
}

.rzig_wrapper_path <- function(path) {
  file.path(path, "R", "rzig-wrappers.R")
}

.rzig_system2 <- function(
  command,
  arguments,
  action,
  environment = character()
) {
  output <- tryCatch(
    suppressWarnings(system2(
      command,
      arguments,
      stdout = TRUE,
      stderr = TRUE,
      env = environment
    )),
    error = function(error) {
      stop(
        "failed to ", action, ": ", conditionMessage(error),
        call. = FALSE
      )
    }
  )
  status <- attr(output, "status", exact = TRUE)
  if (is.null(status)) {
    status <- 0L
  }
  if (!identical(as.integer(status), 0L)) {
    details <- paste(output, collapse = "\n")
    if (nzchar(details)) {
      details <- paste0(":\n", details)
    }
    stop("failed to ", action, details, call. = FALSE)
  }
  invisible(output)
}

.rzig_merge_namespace <- function(existing, generated, package, old_wrapper) {
  begin <- "# Generated by rzig::document(): begin"
  end <- "# Generated by rzig::document(): end"
  starts <- which(trimws(existing) == begin)
  ends <- which(trimws(existing) == end)
  if (length(starts) != length(ends) || length(starts) > 1L ||
      (length(starts) == 1L && ends < starts)) {
    stop("NAMESPACE contains an incomplete RZig-generated block", call. = FALSE)
  }

  if (length(starts) == 1L) {
    existing <- existing[-seq.int(starts, ends)]
  } else {
    legacy <- sprintf(
      "useDynLib(%s, .registration = TRUE, .fixes = \"C_\")",
      package
    )
    existing <- existing[trimws(existing) != legacy]

    wrapper_matches <- regexec(
      "^([A-Za-z.][A-Za-z0-9._]*)[[:space:]]*<-[[:space:]]*function\\(",
      old_wrapper
    )
    captures <- regmatches(old_wrapper, wrapper_matches)
    old_exports <- vapply(
      captures[lengths(captures) > 1L],
      function(match) match[2L],
      character(1L)
    )
    legacy_exports <- c(
      sprintf("export(%s)", old_exports),
      sprintf("export(\"%s\")", old_exports)
    )
    generated_exports <- generated[grepl("^export\\(", generated)]
    existing <- existing[
      !trimws(existing) %in% unique(c(legacy_exports, generated_exports))
    ]
  }

  while (length(existing) && !nzchar(existing[[length(existing)]])) {
    existing <- existing[-length(existing)]
  }
  if (length(existing)) {
    c(existing, "", generated)
  } else {
    generated
  }
}

.rzig_replace_file <- function(source, destination) {
  dir.create(dirname(destination), recursive = TRUE, showWarnings = FALSE)
  if (!file.copy(source, destination, overwrite = TRUE, copy.mode = TRUE)) {
    stop("failed to update generated file: ", destination, call. = FALSE)
  }
  invisible(destination)
}

.rzig_write_text <- function(text, destination) {
  generated <- tempfile("rzig-generated-")
  on.exit(unlink(generated), add = TRUE)
  writeLines(text, generated, sep = "", useBytes = TRUE)
  .rzig_replace_file(generated, destination)
}

.rzig_read_text <- function(path) {
  if (!file.exists(path)) {
    return(NULL)
  }
  size <- file.info(path)$size
  if (is.na(size) || size == 0) {
    return("")
  }
  text <- readChar(path, size, useBytes = TRUE)
  Encoding(text) <- "unknown"
  text
}

.rzig_copy_tree <- function(source, destination) {
  files <- list.files(
    source,
    all.files = TRUE,
    full.names = TRUE,
    recursive = TRUE,
    include.dirs = FALSE,
    no.. = TRUE
  )
  prefix_length <- nchar(source) + 2L
  relative <- substring(files, prefix_length)
  for (index in seq_along(files)) {
    target <- file.path(destination, relative[index])
    dir.create(dirname(target), recursive = TRUE, showWarnings = FALSE)
    if (!file.copy(files[index], target, overwrite = TRUE, copy.mode = TRUE)) {
      stop("failed to copy RZig asset: ", relative[index], call. = FALSE)
    }
  }
  invisible(destination)
}
